### ISSUE TITLE
一点小的建议

### ISSUE THREAD

**Issue by overtrue** [uuk020/logistics#1]
1. 方法设计挺好的，不过建议修改方法名：

因为从逻辑上来看，输入只有两个参数：1. 单号，2. 渠道。所以变化是第二个参数，但是第二个参数的变化没有必要体现在方法名上，所以可以考虑简化一下：

```php
array query(string $code, $gateway = ['kuaidi100'])
```

这样就够了，第二个你在内部实现的时候都当成数组处理就好了，用户可选，或者传字符串，内部强制转数组。

2. 关于返回值

感觉有必要统一返回值格式，就像我的 easy-sms 一样，在每一个渠道自己的实现逻辑里，格式化为统一的数组模型，这样用户在调用时只需要修改渠道配置即可，不必关注修改渠道导致的返回值格式不一样需要单独写代码去处理。

**Comment by overtrue** [comment]
另外看了一下源代码，Query 可能需要改一下名称，你其实想表单的是各种 API 渠道，所以你可以叫 Gateway/Channel 等词，用 Query 感觉有点奇怪，Query 在大部分时候是动词，通常类名与名称空间是会使用名词优先的。

**Comment by uuk020** [comment]
好的, 谢谢超哥的建议. 我等会修改一下.

**Comment by overtrue** [comment]
还是有问题，每一种接口的返回内容应该也要格式化为统一的。

比如你现在的爱查快递是：

```php
['time' => '2019-01-09 12:11', 'context' => '仓库-已签收'],
```

百度是：

```php
['time' => '1545444420', 'desc' => '仓库-已签收'],
```

也就是说开发者一旦修改网关名称，就得改一下他自己系统里拿到返回值以后的处理代码，这体验会很差，所以我的建议是你应该将全部网关返回的内容都统一格式，这样我这个接口不能用的时候我换另外一个接口就只是改一下配置，而不需要再去动业务代码，有一些已经写到数据库了，不可能我要全部替换一次嘛。

都统一为这样的格式：

```php
[ 
     ['time' => '2019-01-09 12:11:00', 'description' => '广东XX转运中心']
]
```

不管怎么改配置，输出是一致的。

**Comment by uuk020** [comment]
> 还是有问题，每一种接口的返回内容应该也要格式化为统一的。
> 
> 比如你现在的爱查快递是：
> 
> ```
> ['time' => '2019-01-09 12:11', 'context' => '仓库-已签收'],
> ```
> 
> 百度是：
> 
> ```
> ['time' => '1545444420', 'desc' => '仓库-已签收'],
> ```
> 
> 也就是说开发者一旦修改网关名称，就得改一下他自己系统里拿到返回值以后的处理代码，这体验会很差，所以我的建议是你应该将全部网关返回的内容都统一格式，这样我这个接口不能用的时候我换另外一个接口就只是改一下配置，而不需要再去动业务代码，有一些已经写到数据库了，不可能我要全部替换一次嘛。
> 
> 都统一为这样的格式：
> 
> ```
> [ 
>      ['time' => '2019-01-09 12:11:00', 'description' => '广东XX转运中心']
> ]
> ```
> 
> 不管怎么改配置，输出是一致的。

好的, 超哥. 我一会就修改一下, 谢谢
