### ISSUE TITLE
查询到的快递信息不对

### ISSUE THREAD

**Issue by twodogegg** [uuk020/logistics#12]
如图，这是一个我自己这两天在淘宝买的快递，快递查询的结果却是没有，或是其他的快递的？？？这很奇怪了。没有查到还可以理解，因为快递100首页的那个搜索框也查不到，但是居然会查询到错误的结果，这个 快递单号 多查几次，查询的结果会很不同。`75155689993986`，上面这个正确的快递信息 我是用这个接口查的 [实时查询](https://poll.kuaidi100.com/manager/page/document/synquery)

![image](https://user-images.githubusercontent.com/29424625/59629308-20436680-9175-11e9-8d4c-0f14526a1ae2.png)

![image](https://user-images.githubusercontent.com/29424625/59629317-23d6ed80-9175-11e9-9a4e-ef73f8b14a42.png)

```
$logistics = new Logistics();

$result = $logistics->query('75155689993986'); // 第二参数不设,则默认快递100接口
print_r($result);
```

**Comment by uuk020** [comment]
快递100 接口变动, 多了几个参数. 看了一下, 多了temp参数, 这个参数是由JavaScript里面的Math.random()生成的. 我尝试用这个试了几次, 还是错误. 不知道他是怎么验证的.
