### ISSUE TITLE
爱查快递接口返回值处理错误

### ISSUE THREAD

**Issue by taozhipeng1990** [uuk020/logistics#15]
![image](https://user-images.githubusercontent.com/3894069/89803198-1775d700-db65-11ea-8acf-5a1c28c96db1.png)
我wget使用中通快递单号，查询一个已签收的快递，
爱查快递返回的状态值是3
但Logistics类处理时，判断状态为1才是正确查询到数据。
这里处理错误

对上述描述更正
在爱查快递官网查询单号数据正常，使用接口查询返回的是假数据。所以状态为3。
目前问题应该是爱查快递接口更换规则了

**Comment by uuk020** [comment]
嗯，这个问题我在文档说明了。 还是采用其他快递接口， 爱查快递接口是我通过F12看接口请求的， 他那边改了规则，我一时半会解决不了， 所以这个接口不是很稳定。抱歉。
