### ISSUE TITLE
强烈建议。配置做成初始化外部传入的。

### ISSUE THREAD

**Issue by huanBird** [uuk020/logistics#16]
作者的包 ，还是可以的。但是配置文件这一点做的不好，正常情况下。vendor 目录包是不允许修改的。强烈建议配置类。做成public属性。快递参数外部可以配置

**Comment by uuk020** [comment]
好的，我修改一下。

**Comment by uuk020** [comment]
@huanBird 配置文件指的是 Config.php 还是 SupportLogistics.php?

**Comment by uuk020** [comment]
@huanBird  已修改
