### ISSUE TITLE
请问一天能调用几次快递接口？有没有限制？

### ISSUE THREAD

**Issue by yanghaifeng88** [uuk020/logistics#2]
请问一天能调用几次快递接口？有没有限制？

**Comment by uuk020** [comment]
这个我目前没有测试, 抱歉. 我等会测试一下吧.

**Comment by phoenixg** [comment]
同问

**Comment by uuk020** [comment]
据测试随机生成100个运单循环请求, 目前没有限制. 但这些接口都是我抓包得来, 虽然我随机设置user-agent,
但是不够保险, 因此可能请求过多会有限制,就要更换IP来去请求.

**Comment by phoenixg** [comment]
抓包的这些接口稳定吗
