### ISSUE TITLE
快递100有问题，只能查状态为快件处于运输过程中的数据，签收了就不能查了吗？

### ISSUE THREAD

**Issue by guoqingtang** [uuk020/logistics#21]
/**
     * 转为数组.
     *
     * @param array|string $response
     */
    protected function toArray($response)
    {
        $jsonToArray = \json_decode($response, true);
        if (empty($jsonToArray)) {
            $this->response = [
                'status' => 0,
                'message' => '请求发生不知名错误, 查询不到物流信息',
                'error_code' => 0,
                'data' => [],
                'logistics_company' => '',
            ];
        } else {
            if (0 === $jsonToArray['state']) {
                $this->response = [
                    'status' => 1,
                    'message' => 'ok',
                    'error_code' => 0,
                    'data' => $jsonToArray['data'],
                    'logistics_company' => $jsonToArray['com'],
                ];
            } else {
                $this->response = [
                    'status' => 0,
                    'message' => $jsonToArray['message'],
                    'error_code' => $jsonToArray['state'],
                    'data' => [],
                    'logistics_company' => '',
                ];
            }
        }

$jsonToArray['state']这个状态有很多种你怎么只能判断等于0？

**Comment by uuk020** [comment]
嗯嗯，目前在忙其他项目，暂时没空修改。等有时间再修改
